name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        kind: [ 'linux', 'macos', 'windows' ]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: macos
            os: macos-latest
            target: osx-x64
          - kind: windows
            os: windows-latest
            target: win-x64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Build and Publish
      run: dotnet publish -c Release --runtime ${{ matrix.target }} -p:PublishSingleFile=true --self-contained=true
